### ISSUE TITLE
Management tooling

### ISSUE THREAD

**Issue by lukashornych** [lukashornych/evitalab#117]
To make evitaLab even more useful, we want to add several tools for database server/catalog/collection management. 

For management of database server itself we would like to:
- [ ] status 🟢 -> solved in #103 
  - URL, version, API URLs, ...
  - evitaDB runtime configuration
  - basic charts? (heap size, cpu usage, ...) 
- [ ] logs + filtering 🟢 -> solved in #142 

- [ ] JFR tracing (start, stop, download, configuration) 🟢 -> solved in #143 
  - optionally embed JFR visualizer if possible
- [ ] create catalog -> solved in #144 

Cluster management (in future):
- [ ] health, lags
- [ ] master/replica view

![Image](https://github.com/lukashornych/evitalab/assets/13931450/d79596f9-3c79-457b-8a28-98ba1a28c079)

For catalog management we would like to:
- [ ] catalog preview -> solved in #161 
- [ ] query recording -> solved in  #150 
- [ ] time machine 🟢 -> solved in #95
  - catalog version
    - mutation listing with filtering + mutation detail
    - create new catalog from version
- [ ] backup, restore 🟢 -> solved in #147 
- [ ] drop 🟢
- [ ] unload?, load?
- [ ] replace, rename 🟢
- [ ] (un)make readonly
- [ ] create collection
- [ ] consistency
- [ ] API compatibility 
  - REST
  - GraphQL

![Image](https://github.com/lukashornych/evitalab/assets/13931450/6e987807-f133-4b24-aa61-3fd4f56f1598)

Entity collection management:
- [ ] index listing 🟢
  - size
  - consistency
  - recreate
- [ ] drop 🟢
- [ ] rename 🟢

![Image](https://github.com/lukashornych/evitalab/assets/13931450/2562d587-dfe6-4f49-878b-fa9277d9518a)

Items marked with 🟢 have API support in evitaDB and can be implemented. Each section/item will be solved in separate issue.

**Comment by lukashornych** [comment]
Right now, evitaDB supports recording and exporting of JFR events. So we can start with that.

**Comment by lukashornych** [comment]
Maybe we should introduce connection name into toolbars like so

![Image](https://github.com/lukashornych/evitalab/assets/13931450/95d6ed46-e903-406b-a8af-9fb82749d886)

Lots of these tools work on level of evitaDB server/connection and it could be confusing having connection name only in tab name.

@novoj toughs?

**Comment by novoj** [comment]
Yes, but there is a lot of data to read, and it would be nice to recognize the right connection from the tab name without clicking on it. What about picking for each connection random color and prepend this bullet before catalog name? And do that only when there are more than single connection? Or use another emoji: 1️⃣2️⃣3️⃣ ... etc? It scales up to 10 connections which seems reasonable enough.

**Comment by lukashornych** [comment]
After some discussion, we will not render connection name in the toolbars (yet). Instead, we will explore different approach to connections entirely in #149.

**Comment by lukashornych** [comment]
@o-miko Let's focus on following menu items next:

- on connection:
  - create catalog
- on catalog:
  - drop catalog
  - rename catalog
  - replace catalog
  - create collection
- on collection:
  - rename collection
  - drop collection



Let's create these methods in the `EvitaDBDriver` and implement them using the gRPC API. We could then make `ConnectionService.getDriver` publically accessible so that UI components can access the correct driver and call required methods. In the future, I think we should use this approach even for existing methods on `ConnectionService` like `getCatalogs`, i.e. access is through the driver, because the driver is already the nice API for the evitaLab. The connection service could just provide management for connections and the driver.

**Comment by lukashornych** [comment]
@o-miko we will add new action to catalog menu > `Switch to transactional mode` which will appear only if the catalog has `state === CatalogState.WARMING_UP`. It will call `EvitaSessionService.goLiveAndClose` gRPC method. 
To test this, you will need to create new catalog for it.

**Comment by lukashornych** [comment]
I've tested the dialogs and we need to:
- [ ] fix UI (button placement, sizing and colors, window padding, text wrapping) to match other dialogs (maybe create common dialogs to simplify the process)
- [ ] handle exceptions by displaying toaster error notifications
- [ ] when adding new collection, UI is not updated

Otherwise it's working well.

**Comment by lukashornych** [comment]
Things we need to sort out that we couldn't make in time:
- [ ] job type, must change the behavior of the job listing
- [ ] can't import catalog from server
- [ ] we don't import catalog from local file
- [ ] all/none in event selection for record jfr
- [ ] add metadata to job files - title, size, etc.
